### ISSUE TITLE
Search ID or Code error! errcode="32006"

### ISSUE THREAD

**Issue by cmnewfan** [LudySu/LrcJaeger#1]
I can get the lrc id, but i get the error in title in download method. what does the error code mean?

**Comment by LudySu** [comment]
Hi, can you take a screenshot when the error happens? And could you please capture the adb log and upload here?

**Comment by cmnewfan** [comment]
sorry for no reply in such a long time.

i am using your code directly, the situation i met was like this:

first i use 
`final ArrayList<QueryResult> queryList = TTDownloader.query(artist_name, music_title)` 
to get QueryResult

then i choose one item of queryList, and 
`boolean flag = TTDownloader.download(queryList.get(item), FileActivity.currentPlayingTitle);` 

in the download function
`String result = download(item);`

then i get 32006 errcode.

**Comment by LudySu** [comment]
Hi, can you please use the LrcJaeger app to download the lyrics for the same song, may be there's something wrong with the server, if that's the case I can not do anything cause it's owned by a 3rd party company. I am just using their service.

The code you are using looks good to me. If the LrcJaeger app works fine, then could you please capture the adb log output and put it here. You can do this in the Android Studio, or use command line if you want.

**Comment by LudySu** [comment]
Not active for a long time, so closing
