### ISSUE TITLE
Is there any way for me to contribute to this lyrics database?

### ISSUE THREAD

**Issue by blueset** [LudySu/LrcJaeger#2]
有什么方法可以向这个歌词库追加歌词？

**Comment by LudySu** [comment]
你好，这个是千千静听的歌词库，以前可以通过千千静听播放软件或者他们网站提交，现在不知道他们还支持，你可以用千千静听软件试试。但由于已经被百度收购，所以可能没有在维护。
市面上还有更好歌词库例如网易的，以后有时间可能我会添加，你有兴趣也可以研究下。
