### ISSUE TITLE
服务是不是已经停止了？

### ISSUE THREAD

**Issue by cmnewfan** [LudySu/LrcJaeger#5]
两个服务地址都获取不到lrc了。

**Comment by LudySu** [comment]
TT那个可能是吧，好久没用了。网易那个现在还能用，可以参考 https://github.com/LudySu/Synology-LrcPlugin
看readme里的章节“Test web API with curl”有API说明

**Comment by cmnewfan** [comment]
谢谢，把TT这个改装成网易的了。
